### ISSUE TITLE
Problem running report generation on Jenkinks

### ISSUE THREAD

**Issue by jradom** [webnexusmobile/cypress-cucumber-getting-started#6]
Hello,

If I run this code locally
         ./node_modules/.bin/cypress-tags run -e TAGS='@login' --browser chrome
         node ./integration/helpers/addScreenshotsToReports.js
then report is generated successfully.

If I run the same code on jenkins it looks like it completely skipping 
this line.  Is it a way to run your code using npm?

Thanks

Jeff

**Comment by jradom** [comment]
Actually, Node reports internal errors.  Is it a way to use NPM to run your code or some other ways to when using Jenkins?  Please, let me know

Thanks

Jeff

**Comment by jradom** [comment]
error are 

 Error: Cannot find module '/data/jenkins/workspace/ist-cypress-vnv-ui-automation-test/ui/cypress-e2e/addScreenshotsToReports.js'
20:46:36     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
20:46:36     at Function.Module._load (internal/modules/cjs/loader.js:743:27)
20:46:36     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
20:46:36     at internal/main/run_main_module.js:17:47 {
20:46:36   code: 'MODULE_NOT_FOUND',
20:46:36   requireStack: []

and the code is 
         npm install
         aws s3 cp s3://test-automation-usage-only/qeteam/cair/cair_credentials/${role}.json {WORKSPACE}/ui/cypress-e2e/fixtures/rolesnew.json
         ./node_modules/.bin/cypress-tags run -e TAGS="@login" --browser chrome
         node ${WORKSPACE}/ui/cypress-e2e/integration/helpers/addScreenshotsToReports.js

**Comment by jradom** [comment]
not an issue
